# docker-compose.yml

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
      - ./migrations:/app/migrations  # Add this line
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=0
    restart: always